 export const text={
    initial: [
    `Eras una cáscara vacía desde un inicio, sin ambiciones, sin pecados, y aun así llegaste aquí solo por una mala jugada del destino, y lo aceptas, aceptas estar aquí porque tú mismo no puedes perdonarte por lo que tu inacción provocó, todas las vidas que murieron en aquel incendio.
    Un rugido más fuerte resuena en el lugar, miras al frente para ver como el monstruo dejó caer el cuerpo inerte del hombre, como si fuera una mero juguete que perdió su gracia al quedar inservible, por lo tanto se prepara para terminar, extendiendo su mano agarra una alabarda tan larga como su altura.
    Sabes lo que pasará a continuación, no hay otro resultado que pueda evitarlo, y aun así.`,
    `Con cautela te acercas a la criatura, aunque nunca has utilizado un arma sabes que la lanza es una de las armas perfectas para un principiante como tu, tiene un largo alcance que permite a un novato portarla lo suficientemente para poder protegerse, su largo es menor que la alabarda siendo de 1,40 m su longitud, pero es más que suficiente.
    El ser a comenzando a bajar su alabarda con velocidad, el propósito, decapitar el juguete inservible que está en el piso, las alabanzas de los demás juguetes comienzan a intensificarse, su excitación por la masacre de uno de los suyos no causa mas que alegria al monstruo.`,
    `Al bajar por completo su brazo no escucho el sonido que esperaba, el sonido de la carne siendo cortada por su instrumento preferido, no, lo que escuchó era el sonido que hace un juguete, cuando se cansa de jugar con ellos y los termina por cortar por la mitad.
    Mirando hacia su brazo nota algo importante, o mejor dicho ve como su brazo ha desaparecido de su lugar, su vista se desplaza hacia dónde se originó el sonido y lo que ve solo causa una furia incontrolable.`,
    `Vio como la parte que le falta está en el suelo, algo que desde que tiene uso de razonamiento nunca ha sucedido, algo ilógico para el, que se considera un ser hecho para la masacre, él nunca debería de haber perdido un brazo, mucho menos por uno de los juguetes, algo inaceptable para el.
    “¡_▄▄▄▄██████████!” Un rugido desgarrador sale de sus cuerdas bucales, esto siempre funciona para inundar de temor los corazones de sus pequeños juguetes, pero este es diferente, el temor de sus ojos nunca apareció, eso logró enfurecer más.`,
    `“¡_▄▄▄▄██!” su brazo restante se movió de su posición con el propósito de desgarrar la existencia de este juguete que no sabe jugar, se supone que los juguetes no se mueven, se quedan quietos para que pueda romperlos, los juguetes no te atacan, ¡el ataca a los juguetes!
    El juguete aunque lento logró esquivar su golpe, esto lo irrita más, no debe pasar esto, ¡no se supone que deba pasar esto!, su brazo golpeó el suelo provocando que se trizara y el polvo se alce segando por un instante la visión de ambos.`,
    `Guiándote por tus instintos casi inexistentes, logras poner la lanza al frente tuyo, logrando bloquear la embestida de la bestia, el golpe te empuja hacia atrás, haciendo que pierdas el equilibrio.
    El ser ve esto como otra oportunidad para acabar la vida de este juguete defectuoso, con velocidad se impulsa hacia al frente, con la intención de acabar esta molestia.
    La mejor defensa es el ataque, la bestia atacó por impulso, aun cuando ese golpe logró desorientar tus sentidos, nunca dejaste de ver a la bestia, reposicionando tus pies, esperas hasta que la bestia está cerca.`,
    `El temblor en la tierra hace que tu decisión flaquee un poco, aun asi tu determinación por salvar a la persona es más fuerte, en unos segundo el bestia recorre el espacio entre los dos como si fuera nada, es normal para alguien inhumano como eso, utiliza su único brazo bueno para lanzar otro golpe devastador.
    Usas el ataque de la bestia a tu favor, extendiendo la lanza la posicionas para que cuando ese golpe de, termine por ser perforado por la mitad.
    “¡███████▄▄!” tu plan logra su cometido, la lanza perfora toda la extremidad del monstruo, sacando tu lanza del demonio, pegas un salto lo suficiente para poder esquivar la embestida que dio cuando vio que su otro brazos terminó por ser inservible.`,
    `Logras esquivar el ataque del ser, esto te deja en una posición ventajosa, el monstruo no puede levantarse, ya que sus brazos no se lo permiten, es como si un bebe quisiera tratar de usar los brazos para levantarse.
    Aprovechas esa abertura para atacar a las pezuñas del ser, aunque son golpes inexpertos, son los suficientes para lograr tu cometido.
    “¡▄▄▄▄▄▄▄▄__!” Aun incluso en esa posición, el ser no se ha rendido, moviéndose de forma desesperada, trata de ponerse de pie, pero le es imposible.`,
    `Un suspiro sale de ti, has logrado tu cometido en salvar a la persona, aunque el resultado no es lo que esperabas, estás satisfecho con eso, una lastima que otros no compartan tus sentimientos.
    La multitud te está observando, las miradas de odio que recibes de ellos es desconcertante para ti, acabas de destrozar su único método de entretenimiento en este lugar, pero su enojo radica más en él porque destrozaste su diversión.
    Porque para personas como ellos, que cayeron en el pecado de la ira, no pueden comprender el porqué alguien puede arriesgar su existencia por una carne inservible que no logró adaptarse a este entorno.`,
    `Ellos saben el porqué lo hiciste, no tenían que ser genios para resolverlo, porque desde que comenzó todo esto, alejaste la pelea lo más lejos del hombre herido.
    Vez como un nativo de este sitio sostiene la forma rota de aquel hombre que tratas de salvar, un cuchillo está presionando la garganta del hombre, el mensaje está claro, si das un paso más hacia el monstruo, ellos acabaran con la vida del hombre, si tu acabas con la del ser.`,
    `Mata a uno para salvar a muchos, una elección fácil, podrías evitar más muertes, más sufrimientos, pero no puedes, abandonaste a alguien que rogó por tu ayuda antes, nunca podrías hacerlo de nuevo, el solo pensar te enferma, como si fuera un metal ardiendo subiendo por tu columna vertebral, la solo idea de hacerlo es insoportable.
    Te alejas del ser despacio, tratando de evitar cualquier confrontación, ellos al ver también cómo te alejas de su entretenimiento sueltan a la carne inservible, los dos lados caminan a por sus respectivas preocupaciones ignorando la existencia del otro.`
        ],
      finalText:`Cuando llegas donde está el hombre puedes ver como la gratitud resplandece en sus ojos, no hace falta ni una palabra, ya sabes lo que quiere transmitir con solo su mirada.
      Con esfuerzo logras subirlo a tu espalda, sujetando la lanza en una mano y la otra como apoyo para evitar que el hombre caiga, sigues tu camino con pasos pesados, pero tu corazón, tu alma, tu misma existencia está en calma.`
}
//Conectar al level-6-normal